"""empty message

Revision ID: 5ddd56407490
Revises: 2d64e412010c
Create Date: 2025-04-16 11:09:19.909641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddd56407490'
down_revision = '2d64e412010c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pickup_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delivery_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delivery_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('stripe_charge_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_charge_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_charge_id')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('delivery_lng')
        batch_op.drop_column('delivery_lat')
        batch_op.drop_column('pickup_lng')
        batch_op.drop_column('pickup_lat')

    # ### end Alembic commands ###
