"""Add M-Pesa fields to Parcel

Revision ID: 9ccb1e44419c
Revises: 5ddd56407490
Create Date: 2025-04-18 16:10:34.209823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ccb1e44419c'
down_revision = '5ddd56407490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_receipt', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_parcel_checkout_request_id'), ['checkout_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcel_checkout_request_id'))
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('mpesa_receipt')

    # ### end Alembic commands ###
